"""init table

Revision ID: 7270bdfefef5
Revises: 
Create Date: 2026-08-27 16:43:22.724820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7270bdfefef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentapplication',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_model', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentapplication_create_at'), 'agentapplication', ['create_at'], unique=False)
    op.create_index(op.f('ix_agentapplication_created_by'), 'agentapplication', ['created_by'], unique=False)
    op.create_index(op.f('ix_agentapplication_description'), 'agentapplication', ['description'], unique=False)
    op.create_index(op.f('ix_agentapplication_display_name'), 'agentapplication', ['display_name'], unique=False)
    op.create_index(op.f('ix_agentapplication_is_deleted'), 'agentapplication', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agentapplication_name'), 'agentapplication', ['name'], unique=False)
    op.create_index(op.f('ix_agentapplication_updated_by'), 'agentapplication', ['updated_by'], unique=False)
    op.create_table('agentconversation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentconversation_agent_id'), 'agentconversation', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agentconversation_create_at'), 'agentconversation', ['create_at'], unique=False)
    op.create_index(op.f('ix_agentconversation_created_by'), 'agentconversation', ['created_by'], unique=False)
    op.create_index(op.f('ix_agentconversation_is_deleted'), 'agentconversation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agentconversation_name'), 'agentconversation', ['name'], unique=False)
    op.create_index(op.f('ix_agentconversation_updated_by'), 'agentconversation', ['updated_by'], unique=False)
    op.create_table('agentconversationmessage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('contents', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.BigInteger(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentconversationmessage_create_at'), 'agentconversationmessage', ['create_at'], unique=False)
    op.create_index(op.f('ix_agentconversationmessage_created_by'), 'agentconversationmessage', ['created_by'], unique=False)
    op.create_index(op.f('ix_agentconversationmessage_updated_by'), 'agentconversationmessage', ['updated_by'], unique=False)
    op.create_table('agentconversationmessagecontent',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_message_id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentconversationmessagecontent_create_at'), 'agentconversationmessagecontent', ['create_at'], unique=False)
    op.create_index(op.f('ix_agentconversationmessagecontent_created_by'), 'agentconversationmessagecontent', ['created_by'], unique=False)
    op.create_index(op.f('ix_agentconversationmessagecontent_updated_by'), 'agentconversationmessagecontent', ['updated_by'], unique=False)
    op.create_table('agenttool',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenttool_agent_id'), 'agenttool', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agenttool_create_at'), 'agenttool', ['create_at'], unique=False)
    op.create_index(op.f('ix_agenttool_created_by'), 'agenttool', ['created_by'], unique=False)
    op.create_index(op.f('ix_agenttool_is_deleted'), 'agenttool', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agenttool_tool_id'), 'agenttool', ['tool_id'], unique=False)
    op.create_index(op.f('ix_agenttool_updated_by'), 'agenttool', ['updated_by'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_create_at'), 'department', ['create_at'], unique=False)
    op.create_index(op.f('ix_department_created_by'), 'department', ['created_by'], unique=False)
    op.create_index(op.f('ix_department_is_deleted'), 'department', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=False)
    op.create_index(op.f('ix_department_updated_by'), 'department', ['updated_by'], unique=False)
    op.create_table('departmentuser',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departmentuser_create_at'), 'departmentuser', ['create_at'], unique=False)
    op.create_index(op.f('ix_departmentuser_created_by'), 'departmentuser', ['created_by'], unique=False)
    op.create_index(op.f('ix_departmentuser_department_id'), 'departmentuser', ['department_id'], unique=False)
    op.create_index(op.f('ix_departmentuser_is_deleted'), 'departmentuser', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_departmentuser_updated_by'), 'departmentuser', ['updated_by'], unique=False)
    op.create_index(op.f('ix_departmentuser_user_id'), 'departmentuser', ['user_id'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('type', sa.Enum('StdioMCP', 'HttpMCP', 'SKILL', name='tooltype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_create_at'), 'tool', ['create_at'], unique=False)
    op.create_index(op.f('ix_tool_created_by'), 'tool', ['created_by'], unique=False)
    op.create_index(op.f('ix_tool_description'), 'tool', ['description'], unique=False)
    op.create_index(op.f('ix_tool_disabled'), 'tool', ['disabled'], unique=False)
    op.create_index(op.f('ix_tool_is_deleted'), 'tool', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=False)
    op.create_index(op.f('ix_tool_type'), 'tool', ['type'], unique=False)
    op.create_index(op.f('ix_tool_updated_by'), 'tool', ['updated_by'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_create_at'), 'user', ['create_at'], unique=False)
    op.create_index(op.f('ix_user_created_by'), 'user', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_updated_by'), 'user', ['updated_by'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('useragentconversation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useragentconversation_conversation_id'), 'useragentconversation', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_useragentconversation_create_at'), 'useragentconversation', ['create_at'], unique=False)
    op.create_index(op.f('ix_useragentconversation_created_by'), 'useragentconversation', ['created_by'], unique=False)
    op.create_index(op.f('ix_useragentconversation_is_deleted'), 'useragentconversation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_useragentconversation_updated_by'), 'useragentconversation', ['updated_by'], unique=False)
    op.create_index(op.f('ix_useragentconversation_user_id'), 'useragentconversation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useragentconversation_user_id'), table_name='useragentconversation')
    op.drop_index(op.f('ix_useragentconversation_updated_by'), table_name='useragentconversation')
    op.drop_index(op.f('ix_useragentconversation_is_deleted'), table_name='useragentconversation')
    op.drop_index(op.f('ix_useragentconversation_created_by'), table_name='useragentconversation')
    op.drop_index(op.f('ix_useragentconversation_create_at'), table_name='useragentconversation')
    op.drop_index(op.f('ix_useragentconversation_conversation_id'), table_name='useragentconversation')
    op.drop_table('useragentconversation')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_updated_by'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_created_by'), table_name='user')
    op.drop_index(op.f('ix_user_create_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tool_updated_by'), table_name='tool')
    op.drop_index(op.f('ix_tool_type'), table_name='tool')
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_is_deleted'), table_name='tool')
    op.drop_index(op.f('ix_tool_disabled'), table_name='tool')
    op.drop_index(op.f('ix_tool_description'), table_name='tool')
    op.drop_index(op.f('ix_tool_created_by'), table_name='tool')
    op.drop_index(op.f('ix_tool_create_at'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_departmentuser_user_id'), table_name='departmentuser')
    op.drop_index(op.f('ix_departmentuser_updated_by'), table_name='departmentuser')
    op.drop_index(op.f('ix_departmentuser_is_deleted'), table_name='departmentuser')
    op.drop_index(op.f('ix_departmentuser_department_id'), table_name='departmentuser')
    op.drop_index(op.f('ix_departmentuser_created_by'), table_name='departmentuser')
    op.drop_index(op.f('ix_departmentuser_create_at'), table_name='departmentuser')
    op.drop_table('departmentuser')
    op.drop_index(op.f('ix_department_updated_by'), table_name='department')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_is_deleted'), table_name='department')
    op.drop_index(op.f('ix_department_created_by'), table_name='department')
    op.drop_index(op.f('ix_department_create_at'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_agenttool_updated_by'), table_name='agenttool')
    op.drop_index(op.f('ix_agenttool_tool_id'), table_name='agenttool')
    op.drop_index(op.f('ix_agenttool_is_deleted'), table_name='agenttool')
    op.drop_index(op.f('ix_agenttool_created_by'), table_name='agenttool')
    op.drop_index(op.f('ix_agenttool_create_at'), table_name='agenttool')
    op.drop_index(op.f('ix_agenttool_agent_id'), table_name='agenttool')
    op.drop_table('agenttool')
    op.drop_index(op.f('ix_agentconversationmessagecontent_updated_by'), table_name='agentconversationmessagecontent')
    op.drop_index(op.f('ix_agentconversationmessagecontent_created_by'), table_name='agentconversationmessagecontent')
    op.drop_index(op.f('ix_agentconversationmessagecontent_create_at'), table_name='agentconversationmessagecontent')
    op.drop_table('agentconversationmessagecontent')
    op.drop_index(op.f('ix_agentconversationmessage_updated_by'), table_name='agentconversationmessage')
    op.drop_index(op.f('ix_agentconversationmessage_created_by'), table_name='agentconversationmessage')
    op.drop_index(op.f('ix_agentconversationmessage_create_at'), table_name='agentconversationmessage')
    op.drop_table('agentconversationmessage')
    op.drop_index(op.f('ix_agentconversation_updated_by'), table_name='agentconversation')
    op.drop_index(op.f('ix_agentconversation_name'), table_name='agentconversation')
    op.drop_index(op.f('ix_agentconversation_is_deleted'), table_name='agentconversation')
    op.drop_index(op.f('ix_agentconversation_created_by'), table_name='agentconversation')
    op.drop_index(op.f('ix_agentconversation_create_at'), table_name='agentconversation')
    op.drop_index(op.f('ix_agentconversation_agent_id'), table_name='agentconversation')
    op.drop_table('agentconversation')
    op.drop_index(op.f('ix_agentapplication_updated_by'), table_name='agentapplication')
    op.drop_index(op.f('ix_agentapplication_name'), table_name='agentapplication')
    op.drop_index(op.f('ix_agentapplication_is_deleted'), table_name='agentapplication')
    op.drop_index(op.f('ix_agentapplication_display_name'), table_name='agentapplication')
    op.drop_index(op.f('ix_agentapplication_description'), table_name='agentapplication')
    op.drop_index(op.f('ix_agentapplication_created_by'), table_name='agentapplication')
    op.drop_index(op.f('ix_agentapplication_create_at'), table_name='agentapplication')
    op.drop_table('agentapplication')
    # ### end Alembic commands ###
