"""DepartmentAddParentId

Revision ID: c6510b57d8b4
Revises: 7270bdfefef5
Create Date: 2026-08-27 18:30:28.165145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6510b57d8b4'
down_revision: Union[str, Sequence[str], None] = '7270bdfefef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('parent_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'parent_id')
    # ### end Alembic commands ###
